### ISSUE TITLE
FlightCamera breaks when entering a seat after kerbals origin part is destroyed

### ISSUE THREAD

**Issue by numberlesstim** [FirstPersonKSP/FreeIva#397]
Repro steps:

1. Build or load the craft below and launch with only one kerbal in the CrewCabin.
2. Make sure throttle is at 0.
3. Stage once to activate, but not fire the engines.
4. Using FreeIVA move the Kerbal to the cockpit _without entering the seat yet_.
5. Use the mouse to fully pull up the throttle lever
6. Wait until the CrewCabin is destroyed by the engines
7. Try to enter the seat

![Craft](https://github.com/pizzaoverhead/FreeIva/assets/117858473/a522736b-80cd-4fbb-9552-6f89623b8e9e)
[CamBrakerCraft.zip](https://github.com/pizzaoverhead/FreeIva/files/14468352/CamBrakerCraft.zip)

Result:

- Broken FlightCamera, stuck in place only allowing panning with the right mouse button
- Enter/Exit mapview will freeze the FlightCamera entirely
- The kerbal is 'missing' after recovering the vessel

[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/14468372/KSP.log)

**Comment by JonnyOThan** [comment]
See also #399 - For the next release I'm going to try and just fix the broken camera behaviors.  A later release will have to overhaul this system.
