### ISSUE TITLE
Habtech2, HT214 Node Module IVA does not line up with part, stopping the transfer of kerbals in free-iva

### ISSUE THREAD

**Issue by BSSSNAG** [FirstPersonKSP/FreeIva#422]
![screenshot8](https://github.com/FirstPersonKSP/FreeIva/assets/83569489/5c80456c-c2bd-4247-bb41-f9c32b80185e)

[Ksp.log](https://drive.google.com/file/d/1KBMrjHBjZKr4HgZLEd3uQFnGg0I17OzZ/view?usp=sharing)

**Comment by JonnyOThan** [comment]
I can't find anything named "ht214"

**Comment by JonnyOThan** [comment]
I tested the 3 "node" modules and the airlock.  Everything seems fine.  Can you post a craft file or be specific about what parts are involved and how they're attached to each other?
