### ISSUE TITLE
Constant NRE's when entering IVA

### ISSUE THREAD

**Issue by 321nick** [FirstPersonKSP/FreeIva#423]
As the title says, i get this error spammed to log when i enter IVA view, and i cant press Y to start moving around freely.

Im using a lot of other mods, but i dont know which would be incompatible. the part im using specifically is the "Fishhead" cockpit from MK2 expansion, but its listed as compatible. im also using Reviva, but it should also work fine with MK2 expansion, or at the very least it doesnt need explicit compat patches with it, right?

Here is the error:

`
[EXC 00:02:20.777] NullReferenceException: Object reference not set to an instance of an object
	FreeIva.ExtensionMethods.GetModule (Part part, System.Type moduleType) (at <57dce1e97df347adb43c0ec6a13fffd9>:0)
	FreeIva.ExtensionMethods.GetModule[T] (Part part) (at <57dce1e97df347adb43c0ec6a13fffd9>:0)
	FreeIva.KerbalIvaAddon.Update () (at <57dce1e97df347adb43c0ec6a13fffd9>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
` 

Here is the KSP.log: 
[KSP - Copy.log](https://github.com/user-attachments/files/16093560/KSP.-.Copy.log)

If you need anything else, just let me know. anything i can do to help!

**Comment by 321nick** [comment]
> Thanks for the report! This has been fixed but is still pending release. Iirc it’s an interaction with kerbalism.
> 
> dupe of #403

Thats odd. im not using Kerbalism in my mod list. Maybe its something else that causes it?

**Comment by JonnyOThan** [comment]
Ah right, I was thinking of a different issue. This one’s still fixed.
