### ISSUE TITLE
there is possible to get inverse of freeIVA to FreeEVA?

### ISSUE THREAD

**Issue by popos123** [FirstPersonKSP/FreeIva#424]
Hi,
I want to get interior (IVA) to be visable on EVA as part of a part (eg. ship) with transparent windows, so the opposite to that this mod do.
But I see that this mod replace stock part to empty part witch only some wectors (points like airlock) and IVA part to only the external mask, so some functionality is possible to reuse.
I ask for a little help from the creators of this mod, I only have the minimum requirements:
1. Just add IVA model to EVA model (if it is no possibility to do with config just edit with Blender).
2. For start there could be no Windows at all.
3. Lastly the props dont ned to be on EVA (but it will be nice), so the main reason why I'm writing this post, becouse i need to figure out how to show kerbal sitting inside on EVA (stock module from eve seat doesn't work)

**Comment by JonnyOThan** [comment]
I’m having some trouble understanding the request.  Can you describe the *experience* you want and not the details of how it would be done?

My best guess is that you want to see the internals of vessels from outside while on EVA.  That seems pretty straightforward; possibly just using the existing depth masks but maybe you’d prefer seeing through the windows only.

But I don’t understand how that would be accomplished with adding IVA models to EVA models, or props, or any of the rest of it.

**Comment by popos123** [comment]
@JonnyOThan hi, thanks for reply, i only wants to see internals of vessel from outside while on EVA.
Like this:
![image](https://github.com/FirstPersonKSP/FreeIva/assets/43697578/4d7d0141-8317-4f5f-a85d-e47096bef3e9)
Link to my mod:
https://github.com/popos123/JSIAdvTransparentPodsStockConfig

BUT this is NOT a good solution becouse the transparency from inside is translucent, it disappear when i dont want it, etc.

So i want to see always internals as it is like a normal part (eg. ship)

**Comment by JonnyOThan** [comment]
I'm not sure how FreeIva is supposed to help with that.  Seems like a feature for JSIAdvancedTransparentPods.  Similar to this idea: https://github.com/JPLRepo/JSIAdvTransparentPods/issues/2

However it may be slightly related to the way that FreeIva updates the positions of the internal spaces relative to the parts.

Also I would urge you to make your mod additive with existing IVAs rather than replacing the internals.
