### ISSUE TITLE
no colision when unbuckled

### ISSUE THREAD

**Issue by Zmarlyandrzej** [FirstPersonKSP/FreeIva#442]
everytime i press y to unbuckle the kerbal just falls through the rocket and ground i tried reinstalling the mod and there still isnt any collison the only fix that kind of works is alt g for no gravity 
can someone please tell me how to fix this problem?

**Comment by JonnyOThan** [comment]
All support requests must include a log file.  Issues like this are almost always caused by an incorrect installation.  Please use CKAN to minimize the risk of that.
