### ISSUE TITLE
One-off requests for ROCapsules support

### ISSUE THREAD

**Issue by JonnyOThan** [FirstPersonKSP/FreeIva#455]
* ROCapsules/PartConfigs/ApolloBDB/ApolloCMBDB.cfg/PART[ROC-ApolloCMBDB]
* ROCapsules/PartConfigs/ApolloBDB/ApolloProbeDockPortBDB.cfg/PART[ROC-ApolloProbeDockPortBDB]
* ROCapsules/PartConfigs/LEMBDB/ApolloDrogueDockPortBDB.cfg/PART[ROC-ApolloDrogueDockPortBDB]

**Comment by lancisman** [comment]
Hmmm, I wonder who requested this... On a serious term thank you so much for this! I cannot wait until it is released.

**Comment by SofieBrink** [comment]
Might be able to clone the BDB support here, just slightly bigger. I believe they’re the same (if slightly older) models

**Comment by lancisman** [comment]
Not sure it will, since ROCapsules and BDB seems to have different IVAs.
