### ISSUE TITLE
Tubes don't get created in certain part combinations

### ISSUE THREAD

**Issue by SofieBrink** [FirstPersonKSP/FreeIva#457]
Repro:
- Install the FreeIVA 0.2.20.0 Pre-Release
- Install PlanetsideExplorationTechnologies
- Construct the craft below with a PT-M100C command module, a PT-091A 1.25 to 0.9375m adapter and a C-100 Mk II Passive docking port.
- Copy the construction and offset the parts to make the bug more clear.
- Go into freeiva and observe the top hatches.

Craft:
![image](https://github.com/user-attachments/assets/26633f5c-b697-4ab3-9bed-d7f71aa77de3)
[Tube Tester.txt](https://github.com/user-attachments/files/17879055/Tube.Tester.txt) (rename this to .craft)

Expected Results:
![image](https://github.com/user-attachments/assets/8b01d826-c5db-4531-91a7-eec56a69a425)
![image](https://github.com/user-attachments/assets/8ee73ebf-4db9-45fd-ac84-c40744db02c3)

Actual:
![image](https://github.com/user-attachments/assets/1a553ee9-0cea-41e8-ac17-6212d1a01abe)
![image](https://github.com/user-attachments/assets/305c5b0a-b7ec-4fc8-ad59-59f107e12440)

**Comment by SofieBrink** [comment]
Repro with stock parts:

MK1-3 pof, Fl-A10 adapter and a junior docking port.
![image](https://github.com/user-attachments/assets/66113987-6d41-404a-a1c8-5cca9be96e2a)
![image](https://github.com/user-attachments/assets/5748ceb0-14e9-45e7-8e0d-03cae8b67ff6)

**Comment by JonnyOThan** [comment]
The last picture there isn't necessarily a bug - 0.2.20 intentionally hides the tubes when in IVA overlay mode.  But if the same thing happens in actual IVA view (as it does in the planetside example) then that's not intentional.
